
GET http://localhost:8000/api/ok/


###
GET http://localhost:8000/api/

###

GET http://localhost:8000/api/users?limit=4

###

GET http://localhost:8000/api/users

###
GET http://localhost:8000/api/users/2
###

POST http://localhost:8000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJOam9raSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODAzNTYwM30.ClY6-FFRsWtpzTunL0DX_t7LmGiNKq7MoJN3jNHx-RE
Content-Type: application/json

{
    "full_name": "Freshia",
    "email": "fresffaiafa@example.com",
    "contact_phone": "+0987654321",
    "address": "123 Main Street",
    "role": "user"
}

###
PUT http://localhost:8000/api/users/13
Content-Type: application/json

{
    "full_name": "Kevin"
}
###
DELETE http://localhost:8000/api/users/2

###

POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "userId": 36,
    "username": "Freshia",
    "password": "freshia",
    "role":"admin"
}

###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "username": "Freshia",
    "password": "freshia"
}


###
GET http://localhost:8000/api/booking
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOlt7ImZ1bGxfbmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwiYWRkcmVzcyI6IjEyMyBFbG0gU3RyZWV0Iiwicm9sZSI6InVzZXIifV0sInJvbGUiOlt7ImZ1bGxfbmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwiYWRkcmVzcyI6IjEyMyBFbG0gU3RyZWV0Iiwicm9sZSI6InVzZXIifV0sImV4cCI6MTcyMDcwNjM5OH0.RvPMWGLzR-7xhdAxguIN_6NyUau4A-3xyXTesxFycWw

###
POST http://localhost:8000/api/booking
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOlt7ImZ1bGxfbmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwiYWRkcmVzcyI6IjEyMyBFbG0gU3RyZWV0Iiwicm9sZSI6InVzZXIifV0sInJvbGUiOlt7ImZ1bGxfbmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwiYWRkcmVzcyI6IjEyMyBFbG0gU3RyZWV0Iiwicm9sZSI6InVzZXIifV0sImV4cCI6MTcyMDcwNjM5OH0.RvPMWGLzR-7xhdAxguIN_6NyUau4A-3xyXTesxFycWw
Content-Type: application/json

{
    //"user_id": 19,
    "vehicle_id": 2,
    "contact" : "+2447 453 453 23",
    //"location_id": 2,
    "total_amount": 89.97,
    "booking_status": "confirmed"
}
###

GET http://localhost:8000/api/booking/7


###
DELETE http://localhost:8000/api/booking/7

###

GET http://localhost:8000/api/payment

###
POST http://localhost:8000/api/payment
Content-Type: application/json

{
     "booking_id": 32,
    "amount": 89.97,
    "payment_status": "Completed",
    "payment_method": "Credit Card",
    "transaction_id": "txn_1234567890"
}

###

PUT http://localhost:8000/api/payment/8
Content-Type: application/json

{
     "amount": 90
}
###



GET http://localhost:8000/api/payment/8

###
DELETE http://localhost:8000/api/payment/4

###
GET http://localhost:8000/api/customerSupportTickets

###
POST http://localhost:8000/api/customerSupportTickets
Content-Type: application/json

{
    
    "subject": "Vehicle Issue",
    "description": "The vehicle I rented has a flat tire.",
    "status": "open"
}

###

PUT http://localhost:8000/api/customerSupportTickets/12
Content-Type: application/json

{
    "status": "open"
}
###
DELETE http://localhost:8000/api/customerSupportTickets/2

###


GET http://localhost:8000/api/locationBranch

###

POST http://localhost:8000/api/locationBranch
Content-Type: application/json

{
     "name": "Main Branch",
    "address": "123 Main St",
    "contact_phone": "+1112223333"
}

###

PUT http://localhost:8000/api/locationBranch/2
Content-Type: application/json

{
    "name": "Bistro"
}
###
DELETE http://localhost:8000/api/locationBranch/1

###

GET http://localhost:8000/api/fleet

###

POST http://localhost:8000/api/fleet
Content-Type: application/json

{
    "vehicle_id": 2,
    "depreciation_rate": 0.15,
    "current_value": 15000.00,
    "maintenance_cost": 200.00,
    "status": "active"
}

###


GET http://localhost:8000/api/fleet/2
###

GET http://localhost:8000/api/filterFleetInfo/1
###

GET http://localhost:8000/api/fleetInfo
###


PUT http://localhost:8000/api/fleet/2
Content-Type: application/json

{
    "depreciation_rate": 0.12
}
###
DELETE http://localhost:8000/api/fleet/1


###

GET http://localhost:8000/api/vehicle

###

POST http://localhost:8000/api/vehicle
Content-Type: application/json

{
      "rental_rate": 99.99,
    "availability": true
}

###

PUT http://localhost:8000/api/vehicle/1
Content-Type: application/json

{
    "availability": false
}
###

GET http://localhost:8000/api/vehicle/1

###
DELETE http://localhost:8000/api/vehicle/1

###

GET http://localhost:8000/api/vehicleSpecs

###

POST http://localhost:8000/api/vehicleSpecs
Content-Type: application/json

{
    "vehicle_id": 2,
    "manufacturer": "Toyota",
    "model": "Camry",
    "year": 2022,
    "fuel_type": "Petrol",
    "engine_capacity": "2.5L",
    "transmission": "Automatic",
    //"seating_capacity": 5,
    //"color": "Red",
    "features": "Air Conditioning, Power Steering, Bluetooth, Cruise Control"
}

###

PUT http://localhost:8000/api/vehicleSpecs/2
Content-Type: application/json

{
    "fuel_type": "diesel"
}
###

GET http://localhost:8000/api/vehicleSpecs/39

###
DELETE http://localhost:8000/api/vehicleSpecs/1

###

GET http://localhost:8000/api/payment

###

POST http://localhost:8000/api/payment
Content-Type: application/json

{
      "booking_id": 8,
    "amount": 150.75,
    "payment_status": "Completed",
    "payment_method": "Credit Card",
    "transaction_id": "txn_01ABC23DEFG45H"
}

###

PUT http://localhost:8000/api/payment/8
Content-Type: application/json

{
    "fuel_type": "diesel"
}
###

GET http://localhost:8000/api/payment/8

###
DELETE http://localhost:8000/api/payment/1

###

GET http://localhost:8000/api/contact

###

POST http://localhost:8000/api/contact
Content-Type: application/json

{
      "first_name": "Freshia",
    "last_name": "Njoki",
    "email": "freshia@gmail.com",
    "phone_number": "+2547 457 454 34",
    "message": "happy yo be here"
}

###

PUT http://localhost:8000/api/contact/1
Content-Type: application/json

{
    "last_name": "Ruitha"
}
###

GET http://localhost:8000/api/contact/1
###
DELETE http://localhost:8000/api/contact/1

###

POST http://localhost:8000/api/create-payment-intent

###
GET  http://localhost:8000/api/revenue/payments


















